# ---------------------------------------
# Outputs for WordPress on AWS Project
# ---------------------------------------

# Public URL of the Application Load Balancer
output "wordpress_url" {
  description = "Public URL to access the WordPress site"
  value       = aws_lb.wp_alb.dns_name
}

# RDS MySQL database endpoint
output "rds_endpoint" {
  description = "RDS MySQL endpoint used by WordPress"
  value       = aws_db_instance.wordpress.address
}

# Random password used for RDS and EC2 (generated by Secrets Manager)
output "db_password_secret_arn" {
  description = "ARN of the Secrets Manager secret storing the database credentials"
  value       = aws_secretsmanager_secret.wordpress_db.arn
}

# Auto Scaling Group name
output "wordpress_asg_name" {
  description = "Name of the Auto Scaling Group for WordPress EC2 instances"
  value       = aws_autoscaling_group.wp_asg.name
}

# WordPress EFS Mount Target
output "efs_mount_target" {
  description = "Mount target for EFS used to persist WordPress content"
  value       = var.efs_mount_point
}

# IAM Role for EC2 instances
output "wordpress_ec2_iam_role" {
  description = "IAM role attached to WordPress EC2 instances"
  value       = aws_iam_role.wp_ec2_role.name
}

# CloudWatch Dashboard URL (Console View)
output "infrastructure_dashboard_url" {
  description = "Console URL for viewing the Infrastructure CloudWatch Dashboard"
  value       = "https://${var.aws_region}.console.aws.amazon.com/cloudwatch/home?region=${var.aws_region}#dashboards:name=${aws_cloudwatch_dashboard.infrastructure_dashboard.dashboard_name}"
}

output "application_dashboard_url" {
  description = "Console URL for viewing the Application CloudWatch Dashboard"
  value       = "https://${var.aws_region}.console.aws.amazon.com/cloudwatch/home?region=${var.aws_region}#dashboards:name=${aws_cloudwatch_dashboard.application_dashboard.dashboard_name}"
}

# SNS Topic for monitoring alerts
output "sns_alert_topic_arn" {
  description = "SNS topic used for monitoring alerts (CloudWatch)"
  value       = aws_sns_topic.monitoring_alerts.arn
}

output "route53_name_servers" {
  value = aws_route53_zone.main.name_servers
}
